msgpack/msgpack-java

msgpack-core/src/main/java/org/msgpack/core/buffer/ChannelBufferInput.java, msgpack-core/src/main/java/org/msgpack/core/buffer/InputStreamBufferInput.java, msgpack-core/src/test/scala/org/msgpack/core/buffer/MessageBufferInputTest.scala
I found reset() in both `ChannelBufferInput` and `InputStreamBufferInput` close the previous assigned input. I fixed this issue as well as https://github.com/msgpack/msgpack-java/pull/169.
@xerial Can you review this PR too?
=> Close the previous assigned input in MessageBufferInput#reset

msgpack-jackson/src/main/java/org/msgpack/jackson/dataformat/MessagePackFactory.java, msgpack-jackson/src/main/java/org/msgpack/jackson/dataformat/MessagePackGenerator.java, msgpack-jackson/src/test/java/org/msgpack/jackson/dataformat/MessagePackGeneratorTest.java, msgpack-jackson/src/test/java/org/msgpack/jackson/dataformat/MessagePackParserTest.java
Prevent MessagePackGenerator(in msgpack-jackson) from outputting data more than once even if flush() is called again.
=> Fix msgpack generator flush

project/Build.scala
When executing "publishLocal" on sbt, it failed with an error message `[error] javadoc: error - invalid flag: -Xdoclint:none`. I guess the reason why it failed is javadoc doesn't has the option in Java1.7 or before. If all the msgpack-java developers use Java1.8, we have nothing to do to fix this issue. But I don't think the limitation is so good. I fixed this issue but I'm not sure if this change is the best.
@xerial Can you review this PR?
=> Set "-Xdoclint:none" only when the Java is 1.8 or more

msgpack-core/src/main/java/org/msgpack/core/MessagePacker.java, msgpack-core/src/main/java/org/msgpack/core/MessageUnpacker.java, msgpack-core/src/main/java/org/msgpack/core/buffer/ArrayBufferInput.java, msgpack-core/src/main/java/org/msgpack/core/buffer/ByteBufferInput.java, msgpack-core/src/main/java/org/msgpack/core/buffer/ChannelBufferInput.java, msgpack-core/src/main/java/org/msgpack/core/buffer/ChannelBufferOutput.java, msgpack-core/src/main/java/org/msgpack/core/buffer/InputStreamBufferInput.java, msgpack-core/src/main/java/org/msgpack/core/buffer/OutputStreamBufferOutput.java, msgpack-core/src/test/scala/org/msgpack/core/MessagePackerTest.scala, msgpack-core/src/test/scala/org/msgpack/core/MessageUnpackerTest.scala
For https://github.com/msgpack/msgpack-java/issues/173.
=> Remove calling of the old resource in reset()

msgpack-core/src/main/java/org/msgpack/core/buffer/MessageBuffer.java, msgpack-core/src/main/java/org/msgpack/core/buffer/MessageBufferU.java
Some JDK in 1.6.x (and Android) does not have `unsafe.copyMemory(srcObj, srcOffset, dstObj, dstOffset, len)` method, which resolves the object memory address inside JVM, so we cannot replace this method without using JNI.
To fix this problem, I added an universal MessageBuffer implementation (MessageBufferU). This fixes #160.
=> Universal MessageBuffer implementation for supporting Java 6

msgpack-core/src/main/java/org/msgpack/core/MessageUnpacker.java
`readNextLength16` and `readNextLength32` already advances buffer position so `skipValue` should not advance position on Array and MapType.
=> Fix wrong skipValue position count

msgpack-core/src/main/java/org/msgpack/core/buffer/MessageBuffer.java, msgpack-core/src/test/scala/org/msgpack/core/buffer/MessageBufferTest.scala
Fix https://github.com/msgpack/msgpack-java/issues/189. It works on Android4.0.4. I guess this version uses https://android.googlesource.com/platform/libcore/+/bdd17cde8cf675f5d5703aad4dfb565932fb4c50/luni/src/main/java/java/nio/DirectByteBuffer.java.
=> Add the constructors of DirectByteBuffer for old Android

msgpack-core/src/main/java/org/msgpack/core/buffer/MessageBuffer.java, msgpack-core/src/main/java/org/msgpack/core/buffer/MessageBufferU.java
=> #188: Fix for MessageBufferU

msgpack-core/src/main/java/org/msgpack/core/buffer/DirectBufferAccess.java, msgpack-core/src/main/java/org/msgpack/core/buffer/MessageBuffer.java
Fixes for #194: 
- Refactored MessageBuffer to isolate the initialization steps between standard and Java6/Android/GAE platforms. 
- Extracted DirectBufferAccess code to a new file. 
I confirmed with this fix, we can initialize MessageBuffer class in GAE platform.
=> Google App Engine Support

.travis.yml
The current TravisCI e-mail notification setting is effective even to forked repositories. Even if we remove this settings, we still can see the build failure in pull-request page. And also we can use an icon like this  [![Travis CI](https://travis-ci.org/msgpack/msgpack-java.svg?branch=v07-develop)](https://travis-ci.org/msgpack/msgpack-java) to notify build failure.
=> Disable TravisCI e-mail notification

msgpack-jackson/src/main/java/org/msgpack/jackson/dataformat/MessagePackExtendedType.java, msgpack-jackson/src/main/java/org/msgpack/jackson/dataformat/MessagePackParser.java, msgpack-jackson/src/test/java/org/msgpack/jackson/dataformat/MessagePackExtendedTypeTest.java, msgpack-jackson/src/test/java/org/msgpack/jackson/dataformat/MessagePackParserTest.java
In https://github.com/msgpack/msgpack-java/pull/201, we made `org.msgpack.jackson.dataformat.MessagePackParser#getEmbeddedObject` return `org.msgpack.value.ExtendedValue` directly. But `org.msgpack.value.ExtendedValue` shouldn't be exposed from `org.msgpack.jackson.dataformat`, I think. Also, wrapping it with `MessagePackExtendedType` would be useful when the implementation of `org.msgpack.value.ExtendedValue` changes.
=> Make MessagePackParser#getEmbeddedObject return MessagePackExtendedType

msgpack-jackson/src/main/java/org/msgpack/jackson/dataformat/MessagePackParser.java, msgpack-jackson/src/test/java/org/msgpack/jackson/dataformat/MessagePackParserTest.java
Fixing the contract of nextToken to be compliant with com.fasterxml.jackson.core.JsonParser.nextToken() and not throw an EOFException if at the end of the stream. fixes #206
=> Fixing the contract of nextToken to be compliant with com.fasterxml.jackson.core.JsonParser.nextToken(), fixes #206

msgpack-jackson/src/main/java/org/msgpack/jackson/dataformat/MessagePackGenerator.java, msgpack-jackson/src/main/java/org/msgpack/jackson/dataformat/MessagePackParser.java
Added support for BigDecimal, fixes #204 using option 2
=> Added support for BigDecimal, fixes #204

project/Build.scala, project/plugins.sbt, sbt, sonatype.sbt
Upgrade to sbt-sonatype-0.5.0 
- This version improves error handling on 500 error when accessing sonatype REST API. 
- Extract sbt-sonatype related setting into sonatype.sbt
- Enables sonatype related commands (e.g., sonatypeRelease) only at the root project
- publishTo setting is not longer necessary (sbt-sonatype sets this)
=> Upgrade to sbt-sonatype-0.5.0

msgpack-core/src/main/java/org/msgpack/core/buffer/InputStreamBufferInput.java, msgpack-core/src/test/scala/org/msgpack/core/buffer/MessageBufferInputTest.scala
=> Fixes #222: Check available() before calling blocking read

msgpack-jackson/src/main/java/org/msgpack/jackson/dataformat/MessagePackParser.java
Let the caller handle the exception instead of printing
=> Throw IOException in MessagePackParser close instead of printing

README.md, project/plugins.sbt
Add jcheckStyle command to enable code style check.
=> Add a code style checker

.travis.yml, msgpack-core/src/test/scala/org/msgpack/core/buffer/MessageBufferTest.scala, sonatype.sbt
- Fixes .travis.yml config not to use jdk6. This is necessary to run the latest version of checkstyle 
- Add test that uses MessageBufferU for emulating jdk6 and Android
=> Add universal buffer test instead of using jdk6

msgpack-core/src/main/java/org/msgpack/core/MessagePacker.java, msgpack-core/src/main/java/org/msgpack/value/IntegerValue.java, msgpack-core/src/main/java/org/msgpack/value/Variable.java, msgpack-core/src/main/java/org/msgpack/value/impl/ImmutableBigIntegerValueImpl.java, msgpack-core/src/main/java/org/msgpack/value/impl/ImmutableLongValueImpl.java, msgpack-core/src/test/scala/org/msgpack/value/ValueTest.scala
Add a utility method to IntegerValue to detect the most succinct integer type. This is useful when user wants to know which get method (e.g., getByte, getInt, etc. ) should be used to extract values.
=> Fixes #38: Add IntegerValue.mostSuccinctMessageFormat

msgpack-jackson/src/main/java/org/msgpack/jackson/dataformat/MessagePackExtensionType.java, msgpack-jackson/src/main/java/org/msgpack/jackson/dataformat/MessagePackGenerator.java
@komamitsu Can you look at this? #250, and #262 used extended instead of extension. This renames the few variables and methods that used it.
=> Rename Extended to Extension

msgpack-core/src/main/java/org/msgpack/core/buffer/MessageBufferBE.java
java.lang.NoSuchMethodException: org.msgpack.core.buffer.MessageBufferBE.<init>([B)
on MessageBuffer.java:146
=> NoSuchMethodException on bigendian system

msgpack-jackson/src/main/java/org/msgpack/jackson/dataformat/MessagePackFactory.java, msgpack-jackson/src/main/java/org/msgpack/jackson/dataformat/MessagePackParser.java, msgpack-jackson/src/test/java/org/msgpack/jackson/dataformat/ExampleOfTypeInformationSerDe.java
I found a bug during creating an example code for https://github.com/msgpack/msgpack-java/issues/229 and fixed it.
=> Save ObjectCodec in MessagePackParser

msgpack-jackson/src/test/java/org/msgpack/jackson/dataformat/ExampleOfTypeInformationSerDe.java, msgpack-jackson/src/test/java/org/msgpack/jackson/dataformat/MessagePackParserTest.java
I fixed below style errors.
```
[error] src/test/java/org/msgpack/jackson/dataformat/ExampleOfTypeInformationSerDe.java:73: Multiple consecutive blank lines
[error] src/test/java/org/msgpack/jackson/dataformat/ExampleOfTypeInformationSerDe.java:76: '=' の前にホワイトスペースがありません。
[error] src/test/java/org/msgpack/jackson/dataformat/ExampleOfTypeInformationSerDe.java:76: '=' の後にホワイトスペースがありません。
[error] src/test/java/org/msgpack/jackson/dataformat/ExampleOfTypeInformationSerDe.java:77: '=' の前にホワイトスペースがありません。
[error] src/test/java/org/msgpack/jackson/dataformat/ExampleOfTypeInformationSerDe.java:77: '=' の後にホワイトスペースがありません。
[info] checkstyle has succeeded
[error] src/test/java/org/msgpack/jackson/dataformat/MessagePackParserTest.java:673: Blank line before end of file
[trace] Stack trace suppressed: run …
```
=> Fix style errors

msgpack-core/src/main/java/org/msgpack/core/buffer/MessageBufferU.java, msgpack-core/src/test/scala/org/msgpack/core/buffer/MessageBufferTest.scala
Fix https://github.com/msgpack/msgpack-java/issues/282
=> Fix MessageBufferU#copyTo called by sliced buffer

msgpack-core/src/main/java/org/msgpack/value/impl/ImmutableLongValueImpl.java, msgpack-core/src/test/scala/org/msgpack/value/ValueTest.scala
asShort() in ImmutableLongvalueImpl should check isInShortRange() instead of isInByteRange()
=> asShort in ImmutableLongValueImpl should check isInShortRange

msgpack-core/src/main/java/org/msgpack/core/MessagePack.java, msgpack-core/src/main/java/org/msgpack/core/MessagePacker.java, msgpack-core/src/main/java/org/msgpack/core/MessageUnpacker.java
This PR removes Config.getXXX. Although there is some advantage of having getters (replacing the internal field name, add a hook point in future, etc.), this config object is only used for storing configuration values, so I think reducing the code size has much advantage over these benefits.
=> Simplify the config object

msgpack-core/src/main/java/org/msgpack/core/MessageBufferPacker.java, msgpack-core/src/main/java/org/msgpack/core/MessagePacker.java, msgpack-core/src/main/java/org/msgpack/core/MessageUnpacker.java
Makes constructors of MessagePacker and MessageUnpacker protected so
that all users use factory methods of MessagePack interface. This
removes duplication of API and make it easy to understand.
=> Make constructors protected to ensure the single entry point

msgpack-core/src/main/java/org/msgpack/core/MessagePack.java, msgpack-core/src/main/java/org/msgpack/core/MessagePacker.java, msgpack-core/src/main/java/org/msgpack/core/MessageUnpacker.java, msgpack-core/src/test/java/org/msgpack/core/example/MessagePackExample.java, msgpack-core/src/test/scala/org/msgpack/core/MessagePackTest.scala
* This change allows applications to use method-chain syntax to create packer and unpacker with config. For example,
```java
MessageUnpacker unpacker = new UnpackerConfig()
.withStringDecoderBufferSize(16 * 1024)
.withActionOnMalformedString(CodingErrorAction.REPORT)
.withActionOnUnmappableString(CodingErrorAction.REPORT)
.newUnpacker(packedData);
```
* This change makes {Packer,Unpacker}Config immutable. This makes it safe to share a config object.
* This change makes buffer size of InputStreamBufferInput, OutputStreamBufferOutput, and ChannelBuffer{Input,Output} configurable. Configurable buffer size is better because it is trade-off of performance and memory consumption.
=> Support method-chain syntax to create packer and unpacker with immutable config

msgpack-core/src/main/java/org/msgpack/core/buffer/ArrayBufferInput.java
This change adds support to give null to ArrayBufferInput.reset method.
This lets applications control lifecycle of MessageBuffer (such as
releasing it to a buffer pool) before calling ArrayBufferInput.close().
=> Make it possible to make ArrayBufferInput empty

msgpack-core/src/main/java/org/msgpack/core/MessageBufferPacker.java, msgpack-core/src/test/scala/org/msgpack/core/MessageBufferPackerTest.scala
otherwise applications need to call flush() for sure, and we often miss it...
=> MessageBufferPacker.toByteArray flushes packer's internal buffer automatically

msgpack-core/src/main/java/org/msgpack/core/MessageUnpacker.java, msgpack-core/src/main/java/org/msgpack/value/ValueFactory.java
ValueFactory .newBinary, .newString, .newArray and .newMap take a
mutable argument. Some of them used them as a reference and some of them
copied them. This pull-request makes it clear that they copy the
argument by default and try to omit the copy if an extra argument is
set to true.
This change also includes:
* newMap(Value... kvs) method which was previously newMap(Value[] kvs)
* MessageUnpacker.unpackValue removes a duplicated copy of new byte[]
(string and binary) or Value[] (array and map).
=> Make copy and reference clear at ValueFactory

msgpack-core/src/main/java/org/msgpack/value/impl/ImmutableBooleanValueImpl.java, msgpack-core/src/main/java/org/msgpack/value/impl/ImmutableDoubleValueImpl.java
=> asBooleanValue, asNumberValue, asFloatValue methods are missing

msgpack-core/src/main/java/org/msgpack/value/ValueType.java, msgpack-core/src/test/scala/org/msgpack/value/ValueFactoryTest.scala
ExtensionValue doesn't extend RawValue.
Only BinaryValue and StringValue extend RawValue.
=> Extension type is not a raw type

msgpack-core/src/main/java/org/msgpack/value/ValueFactory.java
ImmutableMapValueImpl preserves order of values. This is preferred
behavior because it's preffered if created map objects preserve order of
values when an application forwards a received (or deserialized) objects
into another application without modifying it. This pull-request applies
this preference to MapBuilder.
Performance impact should be small because MapBuilder API is a minor
API.
=> ValueFactory.MapBuilder is preferred to preserve value order

msgpack-core/src/main/java/org/msgpack/core/MessageUnpacker.java
Hi!
I encountered a bug while trying to decode integers that cross buffer boundaries. The problem is that MessageUnpacker.prepareNumberBuffer() calls getNextBuffer() before it has copied the data out of the old buffer, but InputStreamBufferInput.next() reuses the existing byte array. This means that by the time it returns, the remaining bytes from the old buffer have been overwritten with fresh data.
This pull request restructures prepareNumberBuffer() so that it copies the remaining bytes before asking for a new buffer. It fixes my problem and still passes its own test suite.
(This is my first attempt to use GitHub, so please be patient if I've got anything wrong!)
=> Copy old data before fetching new data, to avoid overwriting it

msgpack-core/src/test/java/org/msgpack/core/example/MessagePackExample.java
@naritta 
Could you check this fix? Just changed to use MessageBufferPacker in the example codes.
Thanks.
=> Fix msgpack core usage example

msgpack-core/src/main/java/org/msgpack/core/MessagePack.java, msgpack-core/src/main/java/org/msgpack/core/MessagePacker.java, msgpack-jackson/src/main/java/org/msgpack/jackson/dataformat/MessagePackFactory.java, msgpack-jackson/src/main/java/org/msgpack/jackson/dataformat/MessagePackGenerator.java, msgpack-jackson/src/test/java/org/msgpack/jackson/dataformat/MessagePackGeneratorTest.java
a new pull request after the discussion in the previous one (#314, #313).
this time the patch is made for msgpack 0.8
the changes are same as in the previous pull request (plus changes of the new configuration objects).
=> changing str8 format to be configurable (to use it or not), and injecting Config object to MessagePackFactory

RELEASE_NOTES.md, msgpack-core/src/main/java/org/msgpack/core/MessagePack.java, msgpack-core/src/main/java/org/msgpack/core/MessagePacker.java, msgpack-core/src/test/scala/org/msgpack/core/MessagePackerTest.scala
While testing the config for disabling STR8 output, I found an unreachable code path in packString. This PR fixes the usage of CharsetEncoder used in packString.
=> Fix packString 

msgpack-jackson/README.md, msgpack-jackson/src/main/java/org/msgpack/jackson/dataformat/JsonArrayFormat.java, msgpack-jackson/src/test/java/org/msgpack/jackson/dataformat/MessagePackDataformatForPojoTest.java, msgpack-jackson/src/test/java/org/msgpack/jackson/dataformat/MessagePackDataformatTestBase.java
related to the tip that @komamitsu gave in #313 issue, about adding `@JsonFormat(shape=JsonFormat.Shape.ARRAY)` annotation to made a pojo being serialized as array. The issue with that is most of the times you have tons of pojo's around, and you can't enforce all of them to have this annotation, so I've made some global helper to enforce this serialization format on all of the objects serialized by object mapper.
this helper also was made because jackson doesn't provide any programmatic way to do such thing.
=> adding helper for serialization format of object mapper to be array

msgpack-core/src/main/java/org/msgpack/core/MessageUnpacker.java, msgpack-core/src/test/scala/org/msgpack/core/MessageUnpackerTest.scala
prepareNumberBuffer was assuming that a buffer chunk includes at least
`readLength` bytes of data. Maximum size of `readLength` is 8.
Therefore, a problem could always happen if MessageBufferInput returns
buffer chunks smaller than 8 bytes.
=> Fix MessageUnapcker.prepareNumberBuffer

msgpack-jackson/src/main/java/org/msgpack/jackson/dataformat/JsonArrayFormat.java
Related to #358
Having two entities, similar in fields except one may contain extra one, ObjectMapper will fail to de-serialize as it expects the payload to have exact same number of fields (properties) on the value type object.
Consider such case:
```
Pojo1 {
field1;
field2;
}
Pojo2 {
field1;
}
```
Previous client could handle a case when de-serializing the payload of Pojo2 into Pojo1.
This is totally solvable by adding `@JsonIgnoreProperties` annotation, but since we already have `JsonArrayFormat` as helper for backward-compatibility, thought it also should be part of this utility.
=> Ignoring unknown properties on de-serializing process

msgpack-core/src/main/java/org/msgpack/core/MessagePacker.java
A bug is that 1<<32 is 1 in Java. It must be 1L<<32.
A problem happens packString is called with a String that contains a string (longer than 1<<8 characters) and (shorter than 1<<16 characters) and (longer than 1<<16 bytes in UTF-8).
=> fix 'Unexpected UTF-8 encoder state' error at packString

msgpack-core/src/main/java/org/msgpack/core/MessageUnpacker.java
In a case when a client knows the exact number of elements,
it can use an optimized overriden MessageUnpacker which always returns true
=> Make MessageUnpacker.hasNext overridable

msgpack-core/src/main/java/org/msgpack/core/MessagePack.java, msgpack-core/src/main/java/org/msgpack/core/MessagePacker.java, msgpack-core/src/main/java/org/msgpack/core/MessageUnpacker.java, msgpack-core/src/main/java/org/msgpack/core/buffer/ArrayBufferInput.java, msgpack-core/src/main/java/org/msgpack/core/buffer/ByteBufferInput.java, msgpack-core/src/main/java/org/msgpack/core/buffer/MessageBuffer.java, msgpack-core/src/main/java/org/msgpack/core/buffer/MessageBufferBE.java, msgpack-core/src/main/java/org/msgpack/core/buffer/MessageBufferU.java, msgpack-core/src/test/java/org/msgpack/core/example/MessagePackExample.java, msgpack-core/src/test/scala/org/msgpack/core/MessageUnpackerTest.scala, msgpack-core/src/test/scala/org/msgpack/core/buffer/ByteStringTest.scala, msgpack-core/src/test/scala/org/msgpack/core/buffer/MessageBufferInputTest.scala, msgpack-core/src/test/scala/org/msgpack/core/buffer/MessageBufferTest.scala
=> Add ByteBuffer input support again

msgpack-core/src/main/java/org/msgpack/core/MessageUnpacker.java, msgpack-core/src/main/java/org/msgpack/core/buffer/SequenceMessageBufferInput.java, msgpack-core/src/test/scala/org/msgpack/core/MessageUnpackerTest.scala
When multiple MessageBuffer involved at `unpackString` first bytes can be removed because `resetDecoder` is called multiple times.
=> resetDecoder should be called once per decoding

msgpack-core/src/main/java/org/msgpack/core/MessagePacker.java, msgpack-core/src/test/scala/org/msgpack/core/MessagePackerTest.scala
If write/addPayload is used without any preceding packXXX methods, MessagePacker throws NPE #391
=> Fix #391: Add missing buffer null check

msgpack-core/src/main/java/org/msgpack/core/MessagePacker.java
Android 4.x has a bug in CharsetEncoder where offset calculation is
wrong.
See
- https://github.com/msgpack/msgpack-java/issues/405
- https://github.com/msgpack/msgpack-java/issues/406
=> Avoid using CharsetEncoder of Android 4.x

msgpack-jackson/src/main/java/org/msgpack/jackson/dataformat/ExtensionTypeCustomDeserializers.java, msgpack-jackson/src/main/java/org/msgpack/jackson/dataformat/MessagePackExtensionType.java, msgpack-jackson/src/main/java/org/msgpack/jackson/dataformat/MessagePackFactory.java, msgpack-jackson/src/main/java/org/msgpack/jackson/dataformat/MessagePackParser.java, msgpack-jackson/src/test/java/org/msgpack/jackson/dataformat/MessagePackParserTest.java
For https://github.com/msgpack/msgpack-java/issues/398
=> Jackson typebase ext deser

msgpack-core/src/test/scala/org/msgpack/core/buffer/MessageBufferTest.scala
- http://download.java.net/java/jdk9/docs/api/java/nio/Buffer.html#limit-int-
- http://download.java.net/java/jdk9/docs/api/java/nio/ByteBuffer.html#position-int-
```
[error] /home/travis/build/xuwei-k/msgpack-java/msgpack-core/src/test/scala/org/msgpack/core/buffer/MessageBufferTest.scala:163: ambiguous reference to overloaded definition,
[error] both method position in class ByteBuffer of type (x$1: Int)java.nio.ByteBuffer
[error] and  method position in class Buffer of type ()Int
[error] match expected type ?
[error]         bb.position shouldBe 0
[error]            ^
[error] /home/travis/build/xuwei-k/msgpack-java/msgpack-core/src/test/scala/org/msgpack/core/buffer/MessageBufferTest.scala:164: ambiguous reference to overloaded definition,
[error] both method limit in class ByteBuffer …
```
=> fix ambiguous overload in Java 9

msgpack-core/src/main/java/org/msgpack/core/MessageUnpacker.java, msgpack-core/src/test/scala/org/msgpack/core/MessagePackTest.scala
When a code deals with an Optional<T> value, a common way is to
serialize a Nil value if the value is absent. To deserialize it, we
check whether the next value is nil or not first. If it is nil, skip the
byte. Otherwise, read a value. For this common use case, tryUnpackNil
simplifies the deserialization code. It does "check whether the next
value is nil or not first. If it is nil, skip the byte" in one method
call.
=> Add MessageUnpacker.tryUnpackNil() method

msgpack-core/src/main/java/org/msgpack/core/MessageUnpacker.java, msgpack-core/src/main/java/org/msgpack/core/buffer/MessageBufferU.java, msgpack-core/src/test/scala/org/msgpack/core/MessageUnpackerTest.scala
`readPayload(MessageBuffer)` is usually faster than `readPayload(ByteBuffer)` by using `unsafe.copyMemory`
=> Improve readPayload performance

.travis.yml
travis-ci no longer support oraclejdk7
- https://github.com/travis-ci/travis-ci/issues/7884#issuecomment-308451879
- http://www.webupd8.org/2017/06/why-oracle-java-7-and-6-installers-no.html
=> remove oraclejdk7 test

README.md
https://github.com/sbt/sbt/blob/v1.0.4/notes/1.0.0.markdown
> Drops sbt 0.12 style hyphen-separated key names
=> "test-only" does not work since sbt 1.0

msgpack-core/src/test/scala/org/msgpack/core/MessagePackTest.scala, msgpack-core/src/test/scala/org/msgpack/core/MessageUnpackerTest.scala
JavaConversions is deprecated since Scala 2.12
https://github.com/scala/scala/blob/v2.12.4/src/library/scala/collection/JavaConversions.scala#L59
=> use JavaConverters instead of JavaConversions

msgpack-jackson/src/main/java/org/msgpack/jackson/dataformat/ExtensionTypeCustomDeserializers.java, msgpack-jackson/src/main/java/org/msgpack/jackson/dataformat/MessagePackFactory.java, msgpack-jackson/src/test/java/org/msgpack/jackson/dataformat/MessagePackFactoryTest.java
Fix https://github.com/msgpack/msgpack-java/issues/453
=> Support ObjectMapper#copy with MessagePackFactory

msgpack-core/src/main/java/org/msgpack/value/ValueFactory.java
suppress following warning
https://travis-ci.org/msgpack/msgpack-java/jobs/337228566#L522
```
[warn] /home/travis/build/msgpack/msgpack-java/msgpack-core/src/main/java/org/msgpack/value/ValueFactory.java:231:1: Possible heap pollution from parameterized vararg type java.util.Map.Entry<? extends org.msgpack.value.Value,? extends org.msgpack.value.Value>
[warn]     public static MapValue newMap(Map.Entry<? extends Value, ? extends Value>... pairs)
```
=> add SafeVarargs annotation

build.sbt
Scala 2.12 does not support "-target:jvm-1.7"
=> remove "-target:jvm-1.7" from scalacOptions

build.sbt
to address https://github.com/FasterXML/jackson-databind/issues/1599
With 2.8.10, it degrades the serialization performance of
jackson-dataformat-msgpack down to 62%. So we'd better still use 2.7 for now.
Fix https://github.com/msgpack/msgpack-java/issues/463
=> Update jackson-databind 2.7.9.1

msgpack-core/src/main/java/org/msgpack/core/MessagePacker.java
This PR is a javadoc fix for `MessagePacker.addPayload()` to clarify `packRawStringHeader()` or `packBinaryHeader()` needs to be called separately by the application.
Same documentation already exists for `writePayload()` but was missing from `addPayload()`.
=> Clarify usage in documentation for MessagePacker.addPayload()

msgpack-core/src/main/java/org/msgpack/core/MessageUnpacker.java
Avoid creating MessageBuffer just as a wrapper, MessageBuffer.getBytes() is there for that.
(previously #477)
=> avoid creating MessageBuffer needlessly, convert degenerate switch to if

.travis.yml, msgpack-core/src/main/java/org/msgpack/core/buffer/DirectBufferAccess.java, msgpack-core/src/main/java/org/msgpack/core/buffer/MessageBuffer.java, msgpack-core/src/main/java/org/msgpack/core/buffer/MessageBufferU.java
Switches the MessageBuffer implementation to MessageBufferU for Java versions at least 9,  which solves a couple of problems:
1. On Java 11 (OpenJDK) jdk.internal.ref.Cleaner#clean is not open to reflection and the static initializer of DirectBufferAccess throws an IllegalAccessException.
2. Access to java.nio.DirectByteBuffer may suffer the same problem in the future. For now we just get a warning.
Since MessageBufferU overrides almost all methods of MessageBuffer, while direct ByteBuffers register a cleaner by themself, I don't see why MessageBufferU(ByteBuffer) shouldn't accept direct buffers.
This should also solve bug number #482.
=> Improves MessageBuffer support for Java 11

.github/workflows/CI.yml, .travis.yml
- Use GitHub Actions for regular CIs
- Use Travis CI for testing on Arm64 with openjdk11 https://docs.travis-ci.com/user/multi-cpu-architectures/ It's an emulated environment running on x64 machine.
=> Add GitHub Action workflow (x64) and Travis (arm64) build 

msgpack-jackson/src/main/java/org/msgpack/jackson/dataformat/MessagePackParser.java, msgpack-jackson/src/test/java/org/msgpack/jackson/dataformat/MessagePackParserTest.java, sbt
Fixes https://github.com/msgpack/msgpack-java/issues/526
=> Support numeric types in MessagePackParser.getText()

msgpack-core/src/main/java/org/msgpack/value/ValueFactory.java
fix ValueFactory.newMap(Entry<Value, Value>...pairs), which is currently iterating by 2 when it should be iterating through each passed in pair.
=> fix indexing bug in ValueFactory

msgpack-jackson/README.md, msgpack-jackson/src/main/java/org/msgpack/jackson/dataformat/MessagePackParser.java, msgpack-jackson/src/test/java/org/msgpack/jackson/dataformat/MessagePackParserTest.java
Fixes https://github.com/msgpack/msgpack-java/issues/532
=> Support ext type key in Map

msgpack-core/src/main/java/org/msgpack/core/MessageUnpacker.java, msgpack-core/src/main/java/org/msgpack/value/Variable.java
Prevent having two different unpacking methods in the unpacker: `unpackValue` exclusively use arrays for both arrays and maps , and `unpackValue(Variable)`  uses list and map. This will prevent having two different behaviour when unpacking values and prevent some code duplication.
=> Prevent having two different unpacking methods

msgpack-core/src/main/java/org/msgpack/core/MessageBufferPacker.java
Use the bufferSize of PackerConfig to specify the bufferSize of the ArrayBufferOutput in MessageBufferPacker.
=> Specify the bufferSize of the ArrayBufferOutput

msgpack-jackson/README.md, msgpack-jackson/src/main/java/org/msgpack/jackson/dataformat/MessagePackMapper.java
Add an `ObjectMapper` shorthand, allowing a less verbose initialization:
```java
ObjectMapper objectMapper = new MessagePackMapper();
```
Rather than:
```java
ObjectMapper objectMapper = new ObjectMapper(new MessagePackFactory());
```
It's similar to other dataformat implementation as well, see: https://github.com/FasterXML/jackson-dataformats-binary/tree/master/protobuf#creating-objectmapper
=> Add an ObjectMapper shorthand

msgpack-core/src/main/java/org/msgpack/core/MessageUnpacker.java, msgpack-core/src/test/scala/org/msgpack/core/MessageUnpackerTest.scala
I found `MessageUnpacker#getTotalReadBytes` doesn't return correct size once I invoke `MessageUnpacker#close`.
That's because `MessageUnpacker#close` drops the current buffer without updating the read size
https://github.com/msgpack/msgpack-java/blob/v0.9.0/msgpack-core/src/main/java/org/msgpack/core/MessageUnpacker.java#L1738-L1740
even though `MessageUnpacker#getTotalReadBytes` requires the size of the latest buffer.
https://github.com/msgpack/msgpack-java/blob/v0.9.0/msgpack-core/src/main/java/org/msgpack/core/MessageUnpacker.java#L261
=> Keep consistent read size after closing MessageUnpacker

README.md
On the [message pack](https://msgpack.org/index.html) mirror of the readme, since this is relatively linked, it attempts to route to the location https://msgpack.org/msgpack/msgpack-java/blob/develop/msgpack-core/src/test/java/org/msgpack/core/example/MessagePackExample.java which subsequently returns a 404. Statically linking the domain should fix this issue and look a lot more professional. I personally almost didn't use this implementation since I did not realize this was an unintentional side effect.
And yes, I'm making a PR to change one line in the README.
=> Fixed examples relative link in README

NOTICE, sonatype.sbt
Change the license name to the SPDX-ID equivalent.
See: https://spdx.org/licenses/
This will Resolve #652
=> Use SPDX-ID in license name

.github/workflows/CI.yml, README.md, build.sbt, msgpack-core/src/main/java/org/msgpack/core/buffer/DirectBufferAccess.java, msgpack-core/src/test/scala/org/msgpack/core/buffer/DirectBufferAccessTest.scala
To use JDK17 + DirectByteBuffer, we need to set two JVM options:
```
--add-opens=java.base/java.nio=ALL-UNNAMED
--add-opens=java.base/sun.nio.ch=ALL-UNNAMED
```
This PR adds:
- CI for JDK17
- Add a workaround even if these JVM options are not set. 
- Add a warning message when DirectByteBuffer is used in JDK17 without setting these JVM options
Related approaches:
- https://github.com/apache/spark/pull/33947 
- https://github.com/apache/spark/pull/34153 (--add-open JVM options to use reflection access)
- https://github.com/airlift/slice/pull/130
Fixes #600
=> Support JDK17

.github/workflows/CI.yml, msgpack-jackson/src/test/java/org/msgpack/jackson/dataformat/benchmark/MessagePackDataformatHugeDataBenchmarkTest.java
This PR does:
- Add `workflow_dispatch` event to the GitHub Action workflows so that we can manually kick the CI with a specific branch
- Increase the test data size used in `org.msgpack.jackson.dataformat.benchmark.MessagePackDataformatHugeDataBenchmarkTest`
=> Small improvement of msgpack-jackson bench

.github/release-drafter.yml, .github/workflows/release-drafter.yml, README.md
Note: CI will be broken because release-drafter requires configuration files in the main branches, not in the PR branch.
=> Introduce release drafter

.github/workflows/CI.yml, build.sbt, msgpack-core/src/main/java/org/msgpack/core/buffer/DirectBufferAccess.java
This also drops JDK7 support. 
An error: 
```
Caused by: java.lang.ClassNotFoundException: java.nio.MemoryBlock
at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
at java.base/java.lang.Class.forName0(Native Method)
at java.base/java.lang.Class.forName(Class.java:421)
at java.base/java.lang.Class.forName(Class.java:412)
at org.msgpack.core.buffer.DirectBufferAccess.<clinit>(DirectBufferAccess.java:84)
```
Related: Remove private DirectByteBuffer(long, int) constructor before JDK 21 GA https://bugs.openjdk.org/browse/JDK-8303083. In JDK21, DirectByteBuffer(long, long) constructor can be used.
=> feature: Support JDK21 (and drop JDK7 support) 

msgpack-jackson/README.md, msgpack-jackson/src/main/java/org/msgpack/jackson/dataformat/MessagePackMapper.java, msgpack-jackson/src/test/java/org/msgpack/jackson/dataformat/MessagePackMapperTest.java
We've already added `MessagePackMapper#handleBigDecimalAsString` in https://github.com/msgpack/msgpack-java/pull/745 to easily handle BigDecimal as String internally. BigInteger has a similar issue and should be handled as well.
This PR adds `MessagePackMapper#handleBigIntegerAndBigDecimalAsString` to handle both BigInteger and BigDecimal as String.
=> Add MessagePackMapper#handleBigIntegerAndBigDecimalAsString

msgpack-core/src/test/scala/org/msgpack/core/MessagePackTest.scala
According to [msgpack format spec](https://github.com/msgpack/msgpack/blob/master/spec.md#formats), positive fix int ranges from 0x00 to 0x7f. The test only covers from 0x00 to 0x79.
=> Fix fixint test in MessagePackTest.

msgpack-core/src/main/java/org/msgpack/value/impl/ImmutableTimestampValueImpl.java
`ImmutableTimestampValueImpl.getData()` shifts `nsec` (which is a 32-bit `int`) by 34 bits.
=> Fix bug in ImmutableTimestampValueImpl.

msgpack-core/src/main/java/org/msgpack/value/Variable.java
```
java.lang.ClassCastException: class [Ljava.lang.Object; cannot be cast to class [Lorg.msgpack.value.Value; ([Ljava.lang.Object; is in module java.base of loader 'bootstrap'; [Lorg.msgpack.value.Value; is in unnamed module of loader 'app')
at org.msgpack.value.Variable$ArrayValueAccessor.array(Variable.java:890)
at org.msgpack.value.Variable$ArrayValueAccessor.immutableValue(Variable.java:851)
at org.msgpack.value.Variable$ArrayValueAccessor.immutableValue(Variable.java:832)
at org.msgpack.value.Variable.immutableValue(Variable.java:1136)
at org.msgpack.value.Variable.toJson(Variable.java:1161)
```
=> Fix ClassCastException when array values is set as List

build.sbt, msgpack-jackson/src/main/java/org/msgpack/jackson/dataformat/JsonArrayFormat.java
Recent PRs from Scala Steward to upgrade `com.fasterxml.jackson.core:jackson-databind` have failed https://github.com/msgpack/msgpack-java/pull/856. This is because a deprecated API referenced by `msgpack-jackson` module was removed in the latest `jackson-databind`. This PR addresses the issue.
=> Bump the version of `jackson-databind`

msgpack-jackson/src/main/java/org/msgpack/jackson/dataformat/MessagePackFactory.java, msgpack-jackson/src/main/java/org/msgpack/jackson/dataformat/MessagePackGenerator.java, msgpack-jackson/src/main/java/org/msgpack/jackson/dataformat/MessagePackParser.java, msgpack-jackson/src/test/java/org/msgpack/jackson/dataformat/MessagePackDataformatForFieldIdTest.java
Jackson core has interfaces for [field ids](https://github.com/FasterXML/jackson-core/blob/e4ac4f85873dc5e9cad8201f4b5b659db03b1f73/src/main/java/com/fasterxml/jackson/core/JsonGenerator.java#L1140-L1157). This is a great opportunity for msgpack, since the protocol allows for integer keys, enabling more advanced binary serialization strategies for further reduced message size.
Current implementation of msgpack-jackson only allows for coercing strings to integers. Implementing the formal interfaces will enable end-to-end map serialization with mixed string/integer keys. [Other msgpack implementations](https://github.com/msgpack/msgpack-python?tab=readme-ov-file#security) already support this.
1. Implement the formal jackson core interface for writing integer keys as field ids instead of …
=> Add support for jackson field ids
