msgpack/msgpack-java

- msgpack-jackson/src/main/java/org/msgpack/jackson/dataformat/MessagePackParser.java
- msgpack-jackson/src/test/java/org/msgpack/jackson/dataformat/MessagePackParserTest.java
For https://github.com/msgpack/msgpack-java/issues/178
> Implement some methods in MessagePackParser

- msgpack-core/src/main/java/org/msgpack/core/MessagePacker.java
- msgpack-core/src/test/scala/org/msgpack/core/MessagePackerTest.scala
> Add MessagePacker.totalWrittenBytes

- msgpack-jackson/src/main/java/org/msgpack/jackson/dataformat/MessagePackParser.java
- msgpack-jackson/src/test/java/org/msgpack/jackson/dataformat/MessagePackParserTest.java
> jackson: Add support for Extended type

- README.md
- project/Build.scala
- project/build.properties
- project/plugins.sbt
- sbt
- Upgrade to the latest stable versions of Scala 2.11.6 and sbt 0.13.8
- Fix doc
- Cleanup plugin
> Upgrade scala and sbt

- project/Build.scala
This fix adds `publishSigned` and `sonatypeRelease` in `sbt release` steps.
> Automate sbt release steps

- project/plugins.sbt
sbt-pgp 1.0.0 is recommended for sbt-0.13.8
> Upgrade sbt-pgp plugin version

- msgpack-jackson/src/main/java/org/msgpack/jackson/dataformat/MessagePackFactory.java
- msgpack-jackson/src/main/java/org/msgpack/jackson/dataformat/MessagePackParser.java
- msgpack-jackson/src/main/java/org/msgpack/jackson/dataformat/Tuple.java
- msgpack-jackson/src/test/java/org/msgpack/jackson/dataformat/MessagePackGeneratorTest.java
- msgpack-jackson/src/test/java/org/msgpack/jackson/dataformat/MessagePackParserTest.java
Fix https://github.com/msgpack/msgpack-java/issues/233
> Issue 233 2

- msgpack-jackson/src/main/java/org/msgpack/jackson/dataformat/MessagePackParser.java
- msgpack-jackson/src/test/java/org/msgpack/jackson/dataformat/MessagePackParserTest.java
Fix https://github.com/msgpack/msgpack-java/issues/231
> Fix wrong convertion fron long to int

- msgpack-jackson/src/main/java/org/msgpack/jackson/dataformat/MessagePackParser.java
- msgpack-jackson/src/test/java/org/msgpack/jackson/dataformat/MessagePackParserTest.java
Fix https://github.com/msgpack/msgpack-java/issues/244
> Support non-string key in jackson-dataformat-msgpack

- msgpack-core/src/main/java/org/msgpack/core/MessageUnpacker.java
- msgpack-core/src/test/scala/org/msgpack/core/MessageUnpackerTest.scala
Fix https://github.com/msgpack/msgpack-java/issues/277
> Take care of incomplete multi-bytes at the tail of buffer

- msgpack-jackson/src/main/java/org/msgpack/jackson/dataformat/MessagePackGenerator.java
- msgpack-jackson/src/test/java/org/msgpack/jackson/dataformat/MessagePackGeneratorTest.java
Fix https://github.com/msgpack/msgpack-java/issues/278
> Handle trailing zeros of BigDecimal in MessagePackGenerator

- msgpack-core/src/test/scala/org/msgpack/core/MessagePackerTest.scala
- msgpack-core/src/test/scala/org/msgpack/core/MessageUnpackerTest.scala
@xerial Can you review these commits?
> V07 fix micro benchmark failure

- msgpack-core/src/main/java/org/msgpack/core/MessageFormat.java
- msgpack-core/src/test/scala/org/msgpack/core/MessagePackTest.scala
@frsyuki Can you review this fix? The bug has existed since v07-development, though.
> Fix MessageFormat.Code#isFixedMap

- msgpack-core/src/main/java/org/msgpack/value/ValueFactory.java
this pull-request optimizes out HashMap building.
> slight optimization of ValueFactory.newMap

- README.md
The source folder has renamed IntelliJIdea13 to IntelliJIdea14.
> Update URL for IntelliJ setting file

- msgpack-core/src/main/java/org/msgpack/core/MessageUnpacker.java
- msgpack-core/src/test/scala/org/msgpack/core/MessageUnpackerTest.scala
This PR is for merging 
https://github.com/msgpack/msgpack-java/pull/341 (Copy old data before fetching new data, to avoid overwriting it)
https://github.com/msgpack/msgpack-java/pull/347 (test for that)
> Merge "Copy old data before fetching new data, to avoid overwriting it" and add test for that

- build.sbt
- project/plugins.sbt
> Add Osgi settings

- msgpack-jackson/src/main/java/org/msgpack/jackson/dataformat/MessagePackFactory.java
- msgpack-jackson/src/main/java/org/msgpack/jackson/dataformat/MessagePackGenerator.java
- msgpack-jackson/src/test/java/org/msgpack/jackson/dataformat/MessagePackGeneratorTest.java
For https://github.com/msgpack/msgpack-java/issues/313#issuecomment-212530342
> Support complex type key in MessagePackGenerator

- msgpack-jackson/README.md
mainly to be consistent with the main README.
> Remove specific version and add SBT example

- msgpack-core/src/main/java/org/msgpack/core/MessageUnpacker.java
- msgpack-core/src/test/scala/org/msgpack/core/MessageUnpackerTest.scala
This method is useful to skip more than 1 elements.
> Adding bulk skip

- msgpack-core/src/main/java/org/msgpack/core/MessagePacker.java
This trivial change will add the Flushable interface to MessagePacker, and is already implemented through flush(). This will be useful to callers who expect a Flushable.
> MessagePacker implements Flushable via flush()

- project/build.properties
sbt-0.13.13 improves the compilation speed.
> Upgrade to sbt 0.13.13

- msgpack-jackson/src/main/java/org/msgpack/jackson/dataformat/MessagePackGenerator.java
- msgpack-jackson/src/test/java/org/msgpack/jackson/dataformat/MessagePackGeneratorTest.java
- msgpack-jackson/src/test/java/org/msgpack/jackson/dataformat/MessagePackParserTest.java
Fix https://github.com/msgpack/msgpack-java/issues/421
> Msgpack jackson serde str as num

- .travis.yml
- project/build.properties
- project/plugins.sbt
fix https://github.com/msgpack/msgpack-java/issues/416
> add Java 9 test

- msgpack-core/src/main/java/org/msgpack/core/MessageBufferPacker.java
- msgpack-core/src/main/java/org/msgpack/core/MessagePacker.java
- msgpack-core/src/main/java/org/msgpack/core/buffer/ArrayBufferOutput.java
- msgpack-core/src/test/scala/org/msgpack/core/MessageBufferPackerTest.scala
> add MessagePacker.clear() method to clear position

- build.sbt
Fix https://github.com/msgpack/msgpack-java/issues/463
> Use jackson-databind 2.8.11.1 for security vulnerability

- msgpack-jackson/src/main/java/org/msgpack/jackson/dataformat/MessagePackFactory.java
- msgpack-jackson/src/test/java/org/msgpack/jackson/dataformat/MessagePackFactoryTest.java
Fix https://github.com/msgpack/msgpack-java/issues/470
> Fix NPE at ObjectMapper#copy with MessagePackFactory

- msgpack-jackson/src/main/java/org/msgpack/jackson/dataformat/MessagePackParser.java
- msgpack-jackson/src/test/java/org/msgpack/jackson/dataformat/MessagePackParserTest.java
Fixes https://github.com/msgpack/msgpack-java/issues/498
> Handle unexpected EOF

- build.sbt
Fixes https://github.com/msgpack/msgpack-java/issues/504
> Update jackson-databind to 2.9.9

- .travis.yml
- build.sbt
jackson-databind 2.9.9.1 and 2.9.9.2 have some security vulnerabilities.
> Use jackson-databind-2.9.9.3

- msgpack-jackson/README.md
- msgpack-jackson/src/test/java/org/msgpack/jackson/dataformat/MessagePackGeneratorTest.java
Takes care of https://github.com/msgpack/msgpack-java/issues/508
> Add test and update README to follow up issue 508

- build.sbt
https://github.com/msgpack/msgpack-java/issues/529 -- jackson 2.11.2 causes some test failures
> use newer version of jackson (2.10.5)

- msgpack-jackson/README.md
- msgpack-jackson/src/main/java/org/msgpack/jackson/dataformat/ExtensionTypeCustomDeserializers.java
- msgpack-jackson/src/test/java/org/msgpack/jackson/dataformat/MessagePackFactoryTest.java
- msgpack-jackson/src/test/java/org/msgpack/jackson/dataformat/MessagePackParserTest.java
Fixes https://github.com/msgpack/msgpack-java/issues/536
> Remove 2 exttype deser APIs

- msgpack-jackson/src/main/java/org/msgpack/jackson/dataformat/MessagePackGenerator.java
- msgpack-jackson/src/test/java/org/msgpack/jackson/dataformat/MessagePackGeneratorTest.java
Fixes https://github.com/msgpack/msgpack-java/issues/534
> Fix a bug that fails to serialize BigDecimal

- .github/workflows/CI.yml
> Run GitHub actions for develop and main branches

- .github/workflows/release.yml
> Use JDK8 for msgpack-java release

- msgpack-jackson/README.md
Fixes https://github.com/msgpack/msgpack-java/issues/598 's original problem
> Add how to internally represent BigDecimal as str to the doc

- .github/release.yml
- .github/workflows/release-drafter.yml
- .github/workflows/release-note.yml
- README.md
> internal: Automatically generate release notes

- .github/workflows/release.yml
- .github/workflows/snapshot.yml
https://github.com/olafurpg/setup-scala/releases/tag/v14
> use `setup-java` instead of deprecated `olafurpg/setup-scala`

- msgpack-core/src/main/java/org/msgpack/core/MessagePacker.java
As the comment says, the check does nothing and can be removed.
> Remove dead code in MessagePacker.

- msgpack-jackson/src/main/java/org/msgpack/jackson/dataformat/ExtensionTypeCustomDeserializers.java
- msgpack-jackson/src/main/java/org/msgpack/jackson/dataformat/JavaInfo.java
- msgpack-jackson/src/main/java/org/msgpack/jackson/dataformat/MessagePackExtensionType.java
- msgpack-jackson/src/main/java/org/msgpack/jackson/dataformat/MessagePackFactory.java
- msgpack-jackson/src/main/java/org/msgpack/jackson/dataformat/MessagePackGenerator.java
- msgpack-jackson/src/main/java/org/msgpack/jackson/dataformat/MessagePackKeySerializer.java
- msgpack-jackson/src/main/java/org/msgpack/jackson/dataformat/MessagePackParser.java
- msgpack-jackson/src/main/java/org/msgpack/jackson/dataformat/MessagePackReadContext.java
- msgpack-jackson/src/main/java/org/msgpack/jackson/dataformat/MessagePackSerializedString.java
- msgpack-jackson/src/test/java/org/msgpack/jackson/dataformat/MessagePackDataformatForPojoTest.java
- msgpack-jackson/src/test/java/org/msgpack/jackson/dataformat/MessagePackDataformatTestBase.java
- msgpack-jackson/src/test/java/org/msgpack/jackson/dataformat/MessagePackGeneratorTest.java
- msgpack-jackson/src/test/java/org/msgpack/jackson/dataformat/benchmark/MessagePackDataformatPojoBenchmarkTest.java
There is room to improve the performance of `jackson-dataformat-msgpack`. This PR addresses them.
> Improve the performance of `jackson-dataformat-msgpack`
